version: "3"
services:
    django-tests:
          build:
            context: .
            dockerfile: Dockerfile.test
    main-django-app:
          build:
           context: .
           dockerfile: Dockerfile
          ports:
             - 8000:8000
